name: lens
description: A talos-lens app
version: 0.0.1
auth:
  heimdallUrl: https://liberal-donkey.dataos.app/heimdall
logLevel: 'DEBUG'
sources:
  - name: sales # profile name
    type: lens
    lensName: 'public:sales-ops'
